name: "my cat fact action"

description: "Get external data with GitHub Actions"

outputs:
  fact:
    description: Resulting cat fact from the https://cat-fact.herokuapp.com/facts api

inputs:
  issueTitle:
    description: "A name for the cat-fact issue"
    required: true
    default: "A cat fact for you"

  catFact:
    description: "the cat fact retreived from a previous action"
    required: true
    default: "Mona is an Octocat"

  repoToken:
    description: "Authentication token, use secrets.GITHUB_TOKEN"
    required: true
    
runs:
  using: "docker"
  image: "Dockerfile"
